### ISSUE TITLE
Link between AMI (SDM) and BUT's AMI-diarization-setup

### ISSUE THREAD

**Issue by hbredin** [desh2608/diarizer#15]
Thanks @desh2608 for this great contribution to the community!

Can you please clarify what the `AMI (SDM)` experimental protocol is?

Does this use BUT's [`only_words`](https://github.com/BUTSpeechFIT/AMI-diarization-setup/tree/main/only_words) reference labels?  
I guess that SDM stands for *Single Distant Microphone*? Does that mean that it relies on the [Microphone array](https://groups.inf.ed.ac.uk/ami/download/) subset of AMI? If so, which microphone has been used?

**Comment by desh2608** [comment]
@hbredin thanks for your comment.

Yes, the AMI setup uses the reference from BUT. (Actually, we prepare both RTTMs -- from BUT and from annotations -- but the scoring is done using BUT's RTTM).

SDM uses the first microphone from array 1, as is the the convention in Kaldi AMI SDM recipe.

**Comment by hbredin** [comment]
Thanks a lot for your answer. Just one final question before I close this issue (to be 100% certain of my understanding):

AMI (SDM) numbers are computed on `{SESSION}.Array1-01.wav` for all 16 {SESSION} in [this list](https://github.com/BUTSpeechFIT/AMI-diarization-setup/blob/main/lists/test.meetings.txt), right?

**Comment by desh2608** [comment]
Yes, correct.

**Comment by hbredin** [comment]
Thanks!
