### ISSUE TITLE
Sharing the expected output as RTTM files?

### ISSUE THREAD

**Issue by hbredin** [desh2608/diarizer#16]
Would it be possible to share the expected output as `RTTM` files as well?
It would make further comparison much easier!

**Comment by desh2608** [comment]
Yes, that's a good idea. However, I am on an internship right now so I will try to upload the different RTTMs when I get some time. Thanks for the suggestion!

**Comment by desh2608** [comment]
@hbredin I have added RTTM outputs for all the recipes. Please feel free to re-open if there are any issues with the uploaded files (it has been a while since I created them).

**Comment by hbredin** [comment]
That's great, thanks! 

I really appreciate the effort -- this will make future comparisons way more reliable!
