### ISSUE TITLE
AliMeeting

### ISSUE THREAD

**Issue by hbredin** [desh2608/diarizer#17]
Can you please confirm that AliMeeting experiments are based on far-field audio?

* train: `Train_Ali_far`
* development: `Eval_Ali/Eval_Ali_far`
* test: `Test_Ali/Test_Ali_far`

**Comment by desh2608** [comment]
Yes, they are based on the far-field audio. You can see [here](https://github.com/desh2608/diarizer/blob/4a95e6be428e0c7bc20aeee5420e3017892e814b/local/prepare_alimeeting.py#L42) that we prepare the far-field version using the [Lhotse recipe](https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/ali_meeting.py).
