### ISSUE TITLE
setup.py Bug report

### ISSUE THREAD

**Issue by DTDwind** [desh2608/diarizer#19]
https://github.com/desh2608/diarizer/blob/6a5f9c6848175a9862defe3ae9f1fc7afd117920/setup.py#L88

I think maybe you're missing a comma in this line (?

**Comment by DTDwind** [comment]
https://github.com/desh2608/diarizer/blob/6a5f9c6848175a9862defe3ae9f1fc7afd117920/setup.py#L70

And maybe `numpy>=1.19.5` set `numpy==1.22.4`, because `numpy==1.24.2` will get error.

**Comment by desh2608** [comment]
Thanks! Would you be willing to make a PR with these changes?

**Comment by DTDwind** [comment]
OK, I will try this.
