### ISSUE TITLE
Citing this repo?

### ISSUE THREAD

**Issue by hbredin** [desh2608/diarizer#21]
Is there a recommended way of citing this repo?

**Comment by hbredin** [comment]
I guess this is it? https://arxiv.org/abs/2212.05271
ICASSP 2023 maybe?

**Comment by desh2608** [comment]
You can cite the original papers for the methods (see README). You can mention this repo URL in a footnote, or cite my GSS paper if you still have space left! It's still a preprint, and for reasons of anonymity, I cannot comment about where it is submitted ;)

**Comment by hbredin** [comment]
Thanks!

PS: this double blind thing is a bit tricky to enforce for papers where the main contribution is an open source library... I feel your pain...

**Comment by hbredin** [comment]
[What a surprise!](https://twitter.com/rdesh26/status/1658901750089228300) We were talking about Interspeech all along!

**Comment by desh2608** [comment]
Haha, I'll update the citation details in README.
