### ISSUE TITLE
queue-ackgpu.pl: No such file or directory

### ISSUE THREAD

**Issue by DTDwind** [desh2608/diarizer#22]
Thank you for your excellent work on this project. 

I believe that this tool can help the community make progress. 

However, I have encountered an issue while using it. 

Specifically, I cannot find the file `queue-ackgpu.pl`, which doesn't seem to be a part of the original files in kaldi's utils directory. 

Moreover, since my computer system currently lacks a cluster, I have set `cmd.sh` to `run.pl`. 

Could you please advise me on how to handle this problem?

`local/pyannote/train_seg_finetune.sh: line 13: utils/queue-ackgpu.pl: No such file or directory`

**Comment by desh2608** [comment]
Sorry about this. `queue-ackgpu.pl` is just a modified version of Kaldi's `queue.pl` utility script that I modified for the CLSP cluster at JHU. You can simply use `queue.pl`.
