### ISSUE TITLE
overlap-aware spectral clustering

### ISSUE THREAD

**Issue by DTDwind** [desh2608/diarizer#25]
Hello,

May I know how to use the overlap-aware feature of spectral clustering? 

When I ran it, I encountered some issues and found that the `SpectralClustering` provided by `scikit-learn` does not have the `overlap_vector` argument. 

Could you please assist me with this? 

Thank you.

```
Best number of neighbors is 13
Number of speakers is 3
Traceback (most recent call last):
  File "diarizer/spectral/sclust.py", line 199, in <module>
    labels = NME_SpectralClustering(
  File "/mnt/HDD/HDD2/DTDwind/displace/diarizer/diarizer/spectral/Spectral_clustering.py", line 101, in NME_SpectralClustering
    return NME_SpectralClustering_sklearn(
  File "/mnt/HDD/HDD2/DTDwind/displace/diarizer/diarizer/spectral/Spectral_clustering.py", line 129, in NME_SpectralClustering_sklearn
    model = SpectralClustering(
TypeError: __init__() got an unexpected keyword argument 'overlap_vector'
```

**Comment by desh2608** [comment]
You need to install scikit-learn from my fork as described in the install instructions. See: https://github.com/desh2608/diarizer/blob/1bfcd0771fdcca81f318f230ab208116de8d9dda/setup.py#L85

**Comment by DTDwind** [comment]
I am not sure why, but when I used `setup.py`, the version of `scikit-learn` I obtained was `1.2.1`. 

However, this problem was resolved when I used 

`pip install https://github.com/desh2608/scikit-learn/releases/download/v0.24.0-dev-overlap/scikit_learn-0.24.dev0-cp38-cp38-linux_x86_64.whl`. 

Thank you.
